### ISSUE TITLE
Problem: Race condition on token get/create

### ISSUE THREAD

**Issue by julianpistorius** [cyverse/django-cyverse-auth#10]
```
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

<details>

```
2017-08-07 17:33:03,246 django_cyverse_auth.token-ERROR [/opt/env/atmo/lib/python2.7/site-packages/django_cyverse_auth/token.py 179] The method for which to 'read' a globus token has changed. Check the code for more details
Traceback (most recent call last):
  File "/opt/env/atmo/lib/python2.7/site-packages/django_cyverse_auth/token.py", line 177, in validate_globus_oauth_token
    auth_token = create_user_token_from_globus_profile(user_profile, token)
  File "/opt/env/atmo/lib/python2.7/site-packages/django_cyverse_auth/protocol/globus.py", line 222, in create_user_token_from_globus_profile
    auth_token = create_user_and_token(profile_dict, access_token, expiry, issuer)
  File "/opt/env/atmo/lib/python2.7/site-packages/django_cyverse_auth/models.py", line 161, in create_user_and_token
    auth_token = create_token(user_profile['username'], token_key, token_expire, remote_ip, issuer)
  File "/opt/env/atmo/lib/python2.7/site-packages/django_cyverse_auth/models.py", line 182, in create_token
    issuer=issuer)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/opt/env/atmo/lib/python2.7/site-packages/django_cyverse_auth/models.py", line 279, in _atomic_get_token
    key=token_key, user=user)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 114, in execute
    return real_execute(self, sql, params)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 428, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

</details>

The problem is here:

https://github.com/cyverse/django-cyverse-auth/commit/b4c48f67c0413cd05dfd5e9d64837bb47237d173#diff-2287123869f4f7eda35519441b3cb6b9R278

The symptoms are an 'infini-spinner' on login, or a red 'invalid credentials' error banner.

It is a bit tricky to reproduce (timing dependent), but I think I could do it with a carefully constructed test case.

**Comment by julianpistorius** [comment]
<img width="1439" alt="screen shot 2017-08-07 at 4 46 15 pm" src="https://user-images.githubusercontent.com/742633/29050512-42e57c10-7b91-11e7-9aec-ccc8458ad839.png">

**Comment by julianpistorius** [comment]
![screen shot 2017-08-07 at 4 46 48 pm](https://user-images.githubusercontent.com/742633/29050511-42df7fc2-7b91-11e7-886c-93db79874be7.png)

**Comment by steve-gregory** [comment]
@julianpistorius thanks for the write-up, this is something we're looking at fixing in the coming weeks.

**Comment by cdosborn** [comment]
These docs seem relevant.
> Avoid catching exceptions inside atomic! When exiting an atomic block, Django looks at whether it’s exited normally or with an exception to determine whether to commit or roll back. If you catch and handle exceptions inside an atomic block, you may hide from Django the fact that a problem has happened. This can result in unexpected behavior. This is mostly a concern for DatabaseError and its subclasses such as IntegrityError.
https://docs.djangoproject.com/en/1.11/topics/db/transactions/
