### ISSUE TITLE
Error with KeystoneAuth

### ISSUE THREAD

**Issue by xuhang57** [cyverse/django-cyverse-auth#13]
Cannot pass the `https://server_url/auth`now with `v27` branch of the atmosphere using keystone auth beackend now. This is the error that I am getting. Cannot figure out a solution yet. 

```
2017-08-16 11:17:07,377 django.request-ERROR [/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/exception.py 135] Internal Server Error: /auth
Traceback (most recent call last):
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/env/atmo/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/opt/env/atmo/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/env/atmo/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/dev/atmosphere/api/auth.py", line 50, in post
    login(request, user)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 139, in login
    request.session.cycle_key()
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 311, in cycle_key
    self.create()
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 83, in save
    obj = self.create_model_instance(data)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 69, in create_model_instance
    session_data=self.encode(data),
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 98, in encode
    serialized = self.serializer().dumps(session_dict)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/signing.py", line 93, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <keystoneauth1.session.Session object at 0x7f0fae4f4490> is not JSON serializable
```

**Comment by xuhang57** [comment]
solved

**Comment by xuhang57** [comment]
https://github.com/cyverse/django-cyverse-auth/pull/15
